#!/bin/sh
#
# This file is distributed as part of Xilinx ARM SDK
#
# Copyright (c) 2020 - 2021,  Xilinx, Inc.
# All rights reserved.
#
umount /mnt/boot
mount /dev/$1 /mnt/boot
cd /mnt/boot
chainboot

