#!/bin/bash
#
# This file is distributed as part of Xilinx ARM SDK
#
# Copyright (c) 2020 - 2021,  Xilinx, Inc.
# All rights reserved.
#

if [ ! -r /tmp/runpppd ]; then
    touch /tmp/runpppd
    runpppd
fi
