#
# This file is distributed as part of Xilinx ARM SDK
#
# Copyright (c) 2020 - 2021,  Xilinx, Inc.
# All rights reserved.
#
CC=gcc
sdk_version: sdk_version_util.c
	$(CC) -o $(OUT)sdk_version_util sdk_version_util.c -DSDKVERSION=$(SDK_VERSION)
